name: Deploy Evaluation Function to GCP

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "The environment to deploy to"
        required: false
      api-url:
        type: string
        description: "The URL of the backend API"
        required: false
      image-name:
        type: string
        description: "The name of the Docker image to deploy"
        required: true
      function-name:
        type: string
        description: "The name of the Lambda function to deploy"
        required: true
      region:
        type: string
        description: "The GCP region to deploy to"
        default: "europe-west2"
        required: false
      repo:
        type: string
        description: "The image repo"
        required: true
    secrets:
      function-admin-api-key:
        description: "The API key for the Lambda Feedback function admin API"
        required: false
      gcp_credentials:
        description: "The JSON key for deploying to GCP"
        required: true

jobs:
  deploy:
    name: Deploy (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'deploy'
      run: |
        gcloud run deploy ${{inputs.function-name}} \
          --image ${{inputs.repo}}/${{inputs.image-name}} \
          --region ${{inputs.region}} \
          --platform managed
